config/routes.rb
Pdfl3::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  resources :userlocations

  resources :resorts
  
  root :to => 'userlocations#index'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/show', to: 'resorts#index'

end

app/models/resort.rb
class Resort < ActiveRecord::Base
	
  attr_accessible :address, :area, :city, :elevation_base, :elevation_peak, :lifts, :longest_trail, :name, :pr_advanced, :pr_beginner, :pr_expert, :pr_intermediate, :runs, :state, :trail_map, :url, :vertical_drop, :zip, :latitude, :longitude, :snowcountryid





end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  # GET /resorts
  # GET /resorts.json
  def index
    require 'open-uri'
    require 'json'


    # @resorts = Resort.order("cast(verticalDrop as int) desc")
    @resorts = Resort.all


    # Boundaries for the map
    @lat_max = [Resort.maximum("latitude"),session[:uLat]].max
    @lng_max = [Resort.maximum("longitude"),session[:uLng]].max
    @lat_min = [Resort.minimum("latitude"),session[:uLat]].min
    @lng_min = [Resort.minimum("longitude"),session[:uLng]].min
    #@map_bound = "sw?:#{lat_min},#{lng_min},ne?:#{lat_max},#{lng_max}"
    # @map_bound = "#{lat_min},#{lng_min},#{lat_max},#{lng_max}"
    

    # Query the Google Distance Matrix API

    # (1/2) Build destination & origin strings (all zip codes in order)
    dest_str =""
    @resorts.each do |resort|
      if dest_str.empty?
        dest_str ="#{resort.latitude},#{resort.longitude}"
      else
        dest_str = "#{dest_str}|#{resort.latitude},#{resort.longitude}"
      end
    end
    org_str = "#{session[:uLat]},#{session[:uLng]}"
    @dest_str = dest_str
    
    # # (2/2) Drop into URL and poll Google  
    # gmatrix_url = "http://maps.googleapis.com/maps/api/distancematrix/json?origins=#{org_str}&mode=driving&units=imperial&sensor=false&destinations=#{dest_str}"
    # @gmatrix_result = ActiveSupport::JSON.decode(open(URI.encode(gmatrix_url)).read)
    # # maybe split preceding line and check the open function is json
    # # note: distance int is in metres, time is in seconds

    # # drop the time values into an array so we can query the min and max
    # drive_times = []
    # @resorts.each do |resort|
    #   drive_times << @gmatrix_result["rows"][0]["elements"][resort.id - 1]["duration"]["value"]
    # end 
     @drive_secs_min = Resort.minimum("duration_value")
     @drive_secs_max = Resort.maximum("duration_value")
     @price_max = Resort.maximum("price")
     @price_min = Resort.minimum("price")


    # # HAMWeather API (note: huge data return, rate-limited)
    # dest_str_csv = dest_str.gsub('|',',/forecasts/')
    # ham_id = "ONgIFsqwY9VDB0vCdEr2t"
    # ham_token = "cYqMYSEFJjWEGQJ79ULJCM1xzhPAr0HIgpWJL9da"
    # @hweather_url = "http://api.aerisapi.com/batch?requests=/forecasts/#{dest_str_csv}&client_id=#{ham_id}&client_secret=#{ham_token}"
    # @hweather_result = ActiveSupport::JSON.decode(open(URI.encode(@hweather_url)).read)

    # OpenSnow.com API (note: needs attribution)
    # (1) Get list of IDs
    # @opensnowidstr = ""
    # oslocs = %w[NY ME MA CT NH VT]
    # oslocs.each do |w|
    #   osid_url = "http://opensnow.com/api/getLocationIds.php?apikey=mattboys&state=#{w}&type=json"
    #   @osid_result = ActiveSupport::JSON.decode(open(URI.encode(osid_url)).read)
    # end 
     
    # Snocountry (free to 12/26, then paid)
    #apiKey=angel921.hacksam56
    # sc_url = "http://feeds.snocountry.com/conditions.php?apiKey=angel921.hacksam56&regions=northeast"
    sc_url = "http://feeds.snocountry.com/conditions.php?apiKey=angel921.hacksam56&regions=northeast"
    @sc_result = ActiveSupport::JSON.decode(open(URI.encode(sc_url)).read)
    scArray = @sc_result["items"]
    
    #@resorts.each do |resort| 
      # find the hash in scArray where id == resort.snocountry_id

      ## slow way:
      # scx = scArray.find { |h| h["id"] == resort.snowcountry_id}

      ## fast way (build a hash):
      #Hash[scArray.map { |h| h.values_at('id','newSnowMin')}]
      @scHash = scArray.inject({}) {|h,i| h[i["id"]]=i; h}

      # figure out star rating for each resort
      @scHash.each do |k, v|

          case v["primarySurfaceCondition"]
          when 'Packed Powder'
            p1 = 3
          when 'Powder'
            p1 = 4
          when 'Hard Pack'
            p1 = 2
          when 'Lose Granular'
            p1 = 3
          when 'Frozen Granular'
            p1 = 2
          when 'Wet Packed'
            p1 = 2
          when 'Wet Granular'
            p1 = 1
          when 'Wet Snow'
            p1 = 2
          when 'Spring Conditions'
            p1 = 3
          when 'Windblown'
            p1 = 2
          when 'Corn Snow'
            p1 = 1
          when 'Icy'
            p1 = 1
          when 'Variable Conditions'
            p1 = 2
          else
            p1 = 0
          end      
             
         case v["forecastBaseTemp"].to_i 
         when v["forecastBaseTemp"].to_i < 0
          p2 = 0
        when 0..15
          p2 = 1
        when 16..25
          p2 = 2
        when 26..35
          p2 = 3
        when 36..45
          p2 = 4
        when 46..55
          p2 = 1
        else
          p2 = 0
        end 

        p3 = [v["avgBaseDepthMin"].to_i/6,4].min
        p4 = [v["newSnowMin"].to_i/3,3].min

        case v["nightGrooming"]
        when "yes"
          p5 = 3
        else 
          p5 = 0
        end

        p6 = v["openDownHillTrails"].to_i / 20

         v["stars"] = (p1 + p2 + p3 + p4 + p5 + p6)

     end

        
     @c = @resorts.map do |resort|
        
        resort["resortStatus"] = @scHash[resort["snowcountry_id"].to_s]["resortStatus"]
        resort["openDownHillTrails"] = @scHash[resort["snowcountry_id"].to_s]["openDownHillTrails"]
        resort["openDownHillLifts"] = @scHash[resort["snowcountry_id"].to_s]["openDownHillLifts"]
        resort["newSnowMin"] = @scHash[resort["snowcountry_id"].to_s]["newSnowMin"]
        resort["newSnowMax"] = @scHash[resort["snowcountry_id"].to_s]["newSnowMax"]
        resort["snowLast48Hours"] = @scHash[resort["snowcountry_id"].to_s]["snowLast48Hours"]
        resort["primarySurfaceCondition"] = @scHash[resort["snowcountry_id"].to_s]["primarySurfaceCondition"]
        resort["avgBaseDepthMin"] = @scHash[resort["snowcountry_id"].to_s]["avgBaseDepthMin"]
        resort["avgBaseDepthMax"] = @scHash[resort["snowcountry_id"].to_s]["avgBaseDepthMax"]
        resort["snowComments"] = @scHash[resort["snowcountry_id"].to_s]["snowComments"]
        resort["stars"] = @scHash[resort["snowcountry_id"].to_s]["stars"] + (resort.verticaldrop.to_i / 350)
        resort["forecastWeather"] = @scHash[resort["snowcountry_id"].to_s]["forecastWeather"] 

        resort
      end

          # @resorts = Resort.order("cast(verticalDrop as int) desc")
        @resort_sorted = @resorts.sort_by { |h| h[:stars] }.reverse!


   # Resort.prep_for_view()

    # Last thing .. generate page
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resorts }
    end
  end

  # GET /resorts/1
  # GET /resorts/1.json
  def show
    @resort = Resort.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resort }
    end
  end

  # GET /resorts/new
  # GET /resorts/new.json
  def new
    @resort = Resort.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resort }
    end
  end

  # GET /resorts/1/edit
  def edit
    @resort = Resort.find(params[:id])
  end

  # POST /resorts
  # POST /resorts.json
  def create
    @resort = Resort.new(params[:resort])

    respond_to do |format|
      if @resort.save
        format.html { redirect_to @resort, notice: 'Resort was successfully created.' }
        format.json { render json: @resort, status: :created, location: @resort }
      else
        format.html { render action: "new" }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resorts/1
  # PUT /resorts/1.json
  def update
    @resort = Resort.find(params[:id])

    respond_to do |format|
      if @resort.update_attributes(params[:resort])
        format.html { redirect_to @resort, notice: 'Resort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resorts/1
  # DELETE /resorts/1.json
  def destroy
    @resort = Resort.find(params[:id])
    @resort.destroy

    respond_to do |format|
      format.html { redirect_to resorts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/resorts/_form.html.erb
<%= form_for(@resort) do |f| %>
  <% if @resort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resort.errors.count, "error") %> prohibited this resort from being saved:</h2>

      <ul>
      <% @resort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :runs %><br />
    <%= f.number_field :runs %>
  </div>
  <div class="field">
    <%= f.label :pr_beginner %><br />
    <%= f.text_field :pr_beginner %>
  </div>
  <div class="field">
    <%= f.label :pr_intermediate %><br />
    <%= f.text_field :pr_intermediate %>
  </div>
  <div class="field">
    <%= f.label :pr_advanced %><br />
    <%= f.text_field :pr_advanced %>
  </div>
  <div class="field">
    <%= f.label :pr_expert %><br />
    <%= f.text_field :pr_expert %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.number_field :area %>
  </div>
  <div class="field">
    <%= f.label :elevation_base %><br />
    <%= f.number_field :elevation_base %>
  </div>
  <div class="field">
    <%= f.label :elevation_peak %><br />
    <%= f.number_field :elevation_peak %>
  </div>
  <div class="field">
    <%= f.label :vertical_drop %><br />
    <%= f.number_field :vertical_drop %>
  </div>
  <div class="field">
    <%= f.label :longest_trail %><br />
    <%= f.number_field :longest_trail %>
  </div>
  <div class="field">
    <%= f.label :lifts %><br />
    <%= f.number_field :lifts %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :trail_map %><br />
    <%= f.text_field :trail_map %>
  </div>
    <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
    <div class="field">
    <%= f.label :snowcountryid %><br />
    <%= f.text_field :snowcountryid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resorts/_listing.html.erb
<table id="listing-table" class="table"> 
  <tr>
    <th>Latitude (hidden)</th>  <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
    <th>Longitude (hidden)</th>  <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
    <th>Travel Time int (hidden)</th>  <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
    <th>Resort status (hidden)</th>  <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
    <th>Name</th>
    <th>State</th>
    <th>Driving Distance</th>
    <th>Vertical Drop</th>
    <th>Trails Open</th>
    <th>Lifts Open</th>
    <th>New Snow (last 24h)</th>
    <th>Snowfall last 48h</th>
    <th>Primary Surface Condition</th>
    <th>Base depth</th>
    <th>Comments</th>
    <th>Weather Forecast</th>
    <th>Lift Ticket Price</th> <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
    <th>Powderful Star Rating</th>
    <th>Powderful Star Rating (int--hidden)</th> <!--note, keep this col ordering the same; will need to change slider JS if this gets changed -->
  </tr>

<% @resort_sorted.each do |resort| %>
<% if resort.resortStatus == "1" %>
    

  <tr>
    <td><%= resort.latitude %></td> <!-- KEY COLUMN! (currently=1)-->
    <td><%= resort.longitude %></td> <!-- KEY COLUMN! (currently=2)-->
    <td><%= resort.duration_value %></td>   <!-- KEY COLUMN! (currently=3)-->
    <td><%= resort.resortStatus %></td>  <!-- KEY COLUMN! (currently=4)-->
    <td><%= resort.name %></td>
    <td><%= resort.state %></td>
    <td><%= resort.duration_text %></td>
    <td><%= resort.verticaldrop %>ft</td>
    <td><%= resort.openDownHillTrails %></td>
    <td><%= resort.openDownHillLifts %></td>
    <td><%= if resort.newSnowMin == "" 
    			"0" 
    		else
    	 		resort.newSnowMin 
    		end %>" - 
    	<%= if resort.newSnowMax == "" 
    			"0" 
    		else 
				resort.newSnowMax 
			end %>"</td>
    <td><%= if resort.snowLast48Hours == "" 
    			"0" 
    		else 
    			resort.snowLast48Hours 
    		end %>"</td>
    <td><%= resort.primarySurfaceCondition %></td>
    <td><%= resort.avgBaseDepthMin %>" - <%= resort.avgBaseDepthMax %>"</td>
    <td><%= resort.snowComments %></td>
    <td><%= resort.forecastWeather %></td>
    <td>$<%= resort.price %></td> <!-- KEY COLUMN! (currently=17) -->
    <td class="stars"><%= ("★" * (resort.stars / 8).floor) +  ("☆" * (5 - ((resort.stars / 8).floor))) %></td>
    <td><%= (resort.stars / 8).floor %></td> <!-- KEY COLUMN! (currently=19) -->
  </tr>
<% end %>  
<% end %>
</table>

<script>
 // Hide the hidden column
 $("th:nth-child(1),td:nth-child(1),th:nth-child(2),td:nth-child(2),th:nth-child(3),td:nth-child(3),th:nth-child(4),td:nth-child(4),th:nth-child(19),td:nth-child(19)").hide();
 </script>

app/views/resorts/_map.html.erb



<div id="map_canvas">
	<script type="text/javascript">

    // Initialise the map and plot the user's current location
    initialize(<%= session[:uLat] %>,<%= session[:uLng] %>,'You are here')

    //Loop through the resorts table and plot each on the map
    <% @resorts.each do |resort| %>
    <% if resort.resortStatus == "1" %>
	    var rLat = <%= resort.latitude %>
	    var rLng = <%= resort.longitude %>
	    var rTitle = '<%= resort.name %>'
        var stars_rank = '<%= ("★" * (resort.stars / 8).floor) +  ("☆" * (5 - ((resort.stars / 8).floor))) %>'
	    addMarkers(rLat,rLng,rTitle,stars_rank)
    <% end %>
<% end %>

var lat_min = <%= @lat_min %>
var lng_min = <%= @lng_min %>
var lat_max = <%= @lat_max %>
var lng_max = <%= @lng_max %>

zoomToFit(lat_max,lng_max,lat_min,lng_min);

  </script>

</div>	



app/views/resorts/_sliders.html.erb

<!-- variables to pass -->
<script type="text/javascript">
	var drive_secs_min = "<%= @drive_secs_min %>"
	var drive_secs_max = "<%= @drive_secs_max %>"
    var price_min = "<%= @price_min %>"
    var price_max = "<%= @price_max %>"

</script>
<p>
Use the sliders to tailor your perfect trip!
</p>

<br />
<p>
    <label for="amount-distance">Driving time:</time>
    <input type="text" id="amount-distance" style="border: 0; color: #f6931f; font-weight: bold;" />
	<div id="slider-range-distance"></div>
</p>
<br />
<p>
    <label for="amount-conditions">Conditions:</label>
    <input type="text" id="amount-conditions" style="border: 0; color: #f6931f; font-weight: bold;" />
	<div id="slider-range-conditions"></div>
 </p>
 <br />
 <p>
    <label for="amount-price">Price range:</label>
    <input type="text" id="amount-price" style="border: 0; color: #f6931f; font-weight: bold;" />
	<div id="slider-range-price"></div>
 </p>


 

 

app/views/resorts/edit.html.erb
<h1>Editing resort</h1>

<%= render 'form' %>

<%= link_to 'Show', @resort %> |
<%= link_to 'Back', resorts_path %>

app/views/resorts/index.html.erb
 <h1></h1>

<div class="row">
 <div class="span8">
  <%= render "map" %>
 </div>	
 <div class="span4">
  <%= render "sliders" %>
 </div> 
 <h1></h1>
  <%= render "listing" %>

</div>

<p>

 

app/views/resorts/new.html.erb
<h1>New resort</h1>

<%= render 'form' %>

<%= link_to 'Back', resorts_path %>

app/views/resorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resort.name %>
</p>

<p>
  <b>Runs:</b>
  <%= @resort.runs %>
</p>

<p>
  <b>Pr beginner:</b>
  <%= @resort.pr_beginner %>
</p>

<p>
  <b>Pr intermediate:</b>
  <%= @resort.pr_intermediate %>
</p>

<p>
  <b>Pr advanced:</b>
  <%= @resort.pr_advanced %>
</p>

<p>
  <b>Pr expert:</b>
  <%= @resort.pr_expert %>
</p>

<p>
  <b>Area:</b>
  <%= @resort.area %>
</p>

<p>
  <b>Elevation base:</b>
  <%= @resort.elevation_base %>
</p>

<p>
  <b>Elevation peak:</b>
  <%= @resort.elevation_peak %>
</p>

<p>
  <b>Vertical drop:</b>
  <%= @resort.vertical_drop %>
</p>

<p>
  <b>Longest trail:</b>
  <%= @resort.longest_trail %>
</p>

<p>
  <b>Lifts:</b>
  <%= @resort.lifts %>
</p>

<p>
  <b>Url:</b>
  <%= @resort.url %>
</p>

<p>
  <b>Address:</b>
  <%= @resort.address %>
</p>

<p>
  <b>City:</b>
  <%= @resort.city %>
</p>

<p>
  <b>State:</b>
  <%= @resort.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @resort.zip %>
</p>

<p>
  <b>Trail map:</b>
  <%= @resort.trail_map %>
</p>

<p>
  <b>SnowCountry ID:</b>
  <%= @resort.snowcountryid %>
</p>

<%= link_to 'Edit', edit_resort_path(@resort) %> |
<%= link_to 'Back', resorts_path %>