config/routes.rb
Pdfl3::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  resources :userlocations

  resources :resorts
  
  root :to => 'userlocations#index'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/show', to: 'resorts#index'

end

app/views/layouts/_footer.html.erb
<footer>
 

  
 <%= yield :scripts %>

</footer>

app/views/layouts/_header.html.erb

<header>
<div class="container">

      <div id="logo">Powderful</div>
      <nav>
        <ul id="link-options">
          <li><%= link_to "About", root_path %></li>
          <li><%= link_to "Contact", help_path %></li>
          
        </ul>
      </nav>
    </div>
  <!-- </div> -->
</div>
</header>



<!-- <div id="link-options"> -->
    
    

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Powderful.net | Skiing in New England and upstate New York
    </title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
      <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= render 'layouts/shim' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Racing+Sans+One|Faster+One|Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    
 <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    
    

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <% # flash shows error messages %>
        <% flash.each do |key, value| %>
          <div class="alert-alert-<%= key %>"><%= value %></div>
        <% end %>
      
      <%= yield %>

      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>